#
#  Copyright (c) 2020 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation

apiVersion: batch/v1
kind: Job
metadata:
  name: docker-registry-image-copier
  labels:
    app: che
    component: docker-registry
spec:
  template:
    metadata:
      labels:
        app: che
        component: docker-registry
    spec:
      containers:
      - name: skopeo
        image: quay.io/eclipse/che-docker-registry-image-copier:alpine-588433c
        imagePullPolicy: IfNotPresent
        env:
          - name: DOCKER_IMAGES
            value: ''
          - name: DOCKER_REGISTRY
            value: ''
        ttlSecondsAfterFinished: 10
      restartPolicy: Never
  backoffLimit: 4
